name: Publish Python Package on Release

on:
  release:
    types: [published]  # 监听 Release 发布事件

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract version from Release
      id: extract_version
      run: |
        # 提取 Release 的版本号
        RELEASE_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        echo "Extracted version: $RELEASE_VERSION"
        echo "PACKAGE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.15'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*