name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # 触发条件：推送以 'v' 开头的标签时

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract version from tag
      id: extract_version
      run: |
        # 提取 Git 标签并去掉 'v' 前缀
        TAG_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        echo "Extracted version: $TAG_VERSION"
        echo "PACKAGE_VERSION=$TAG_VERSION" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.15'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*